name: Deploy ALONE-MD Bot

on:
  push:
    branches:
      - main  # Ce workflow est exécuté lorsqu'un push est effectué sur la branche 'main'
  pull_request:
    branches:
      - main  # Ce workflow est aussi exécuté lorsqu'une pull request est envoyée vers la branche 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Le workflow utilise un environnement Ubuntu pour exécuter le job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Récupère ton code depuis GitHub

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Installe Node.js dans l'environnement
      with:
        node-version: '16'  # Utilise la version 16 de Node.js pour ton projet

    - name: Install dependencies
      run: |
        npm install  # Installe les dépendances du projet à partir de 'package.json'

    - name: Configure environment variables
      run: |
        echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> $GITHUB_ENV  # Ajoute le token du bot comme variable d'environnement

    - name: Start bot
      run: |
        npm start  # Lance ton bot avec 'npm start' (assure-toi que ton bot démarre ainsi)
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # Utilise le token du bot depuis les secrets GitHub

    - name: Deployment success
      run: |
        echo "Deployment completed successfully!"  # Message indiquant que le déploiement a réussi
